version: '3.9'
services:
  edu-server-app:
    container_name: edu-server-app
    image: edu-server-app
    restart: always
    build: .
    ports:
      - '5080:5000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
